workflows:
  music_excellence_ios:
    name: Music Excellence iOS
    max_build_duration: 60
    environment:
      vars:
        XCODE_WORKSPACE: "ios/App.xcworkspace"
        XCODE_SCHEME: "App"
      xcode: latest
    scripts:
      - name: Install dependencies
        script: |
          npm install
          npm install -g @capacitor/cli
      - name: Build web assets
        script: |
          npm run build || echo "No build script, skipping"
      - name: Copy web assets to iOS
        script: |
          npx cap sync ios
      - name: Open iOS project
        script: |
          cd ios
          pod install
      - name: Build iOS
        script: |
          xcodebuild clean archive \
            -workspace "$XCODE_WORKSPACE" \
            -scheme "$XCODE_SCHEME" \
            -archivePath $CM_BUILD_DIR/build/App.xcarchive \
            -sdk iphoneos \
            -configuration Release \
            CODE_SIGN_IDENTITY="" \
            CODE_SIGNING_REQUIRED=NO
    artifacts:
      - build/**/*.ipa